// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1bC0HSiY_1O07eOis2FvCmi7-kJvbObY',
    appId: '1:321799251179:web:15063b802276882ea2caae',
    messagingSenderId: '321799251179',
    projectId: 'stillwalking-26bf8',
    authDomain: 'stillwalking-26bf8.firebaseapp.com',
    storageBucket: 'stillwalking-26bf8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZObMuTnofsYKf8ocETJBI8pf57syS-yI',
    appId: '1:321799251179:android:47bd26d17688c54fa2caae',
    messagingSenderId: '321799251179',
    projectId: 'stillwalking-26bf8',
    storageBucket: 'stillwalking-26bf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApdgitWA72-uLvPpFeXug2520SinaCN8k',
    appId: '1:321799251179:ios:220f227ab4f74395a2caae',
    messagingSenderId: '321799251179',
    projectId: 'stillwalking-26bf8',
    storageBucket: 'stillwalking-26bf8.appspot.com',
    iosClientId: '321799251179-pvja24cc9ohqibqt2peooah6jibfjm27.apps.googleusercontent.com',
    iosBundleId: 'com.todosqlite.todoSqlite',
  );
}
